version: '3.8'
services:
  app:
    build:
      context: . # Asume que el Dockerfile está en el mismo directorio
    ports:
      - '3000:3000' # Mapea el puerto 3000 del contenedor al puerto 3000 de tu máquina
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - my-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379' # Mapea el puerto 6379 del contenedor al puerto 6379 de tu máquina
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
