services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
